language: ruby
script:
  - ./script/ci/travis
after_script:
  - git status | head -1 | grep '^# On branch master$' > /dev/null && curl --head https://etu.utt.fr/v9/deploy
rvm:
  - 1.9.2
  - 1.9.3
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  email: false
