language: ruby
script:
  - ./script/ci/travis
after_script:
  - curl --silent https://etu.utt.fr/v9/deploy
rvm:
  - 1.9.3
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  email: false
