language: ruby
script:
  - ./script/ci/travis
after_script:
  - git status
  - true
rvm:
  - 1.9.2
  - 1.9.3
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  email: false
