#!/bin/bash

set -u

cd "$(dirname $0)/.."

LOCK_FILE=tmp/deploying
trap "rm -f $LOCK_FILE; echo exit $?; exit $?" INT TERM EXIT
[ -f $LOCK_FILE ] && exit 1 || touch $LOCK_FILE

echo "Starting at $(date)..."

git pull -v origin
bundle install -V --deployment --without test development import
mv -v public/maintenance.html{.NO,}
rake -tv db:migrate RAILS_ENV=production
touch tmp/restart.txt
mv -v public/maintenance.html{,.NO}

echo "Finished at $(date)."

rm -f $LOCK_FILE

