#!/bin/bash

set -e # abort on errors

[ -f tmp/deploying ] && exit 1 || touch tmp/deploying

echo "Starting at $(date)..."

export RAILS_ENV=production

git pull
bundle install --deployment --without test development import
mv public/maintenance.html{.NO,}
rake db:migrate
touch tmp/restart.txt
mv public/maintenance.html{,.NO}

echo "Finished at $(date)."

rm -f tmp/deploying

