#!/bin/bash

set -eu

export RAILS_ENV=test

for file in database settings; do
    cp -n config/$file.yml{.example,}
done

rake tmp:create db:drop db:setup

COVERAGE=1 rake --trace

brakeman -qz --except Redirect

rails_best_practices --spec || true

